### PR TITLE
update from upstream

### PR DESCRIPTION
**Pull request by DrMoriarty**

### CODE REVIEW

**Comment by galexandrov** [comment]
Can you please update the GCDWebServer submodule to the correct sha

**Comment by DrMoriarty** [comment]
done

**Comment by galexandrov** [comment]
Can you check [this](https://github.com/Icenium/cordova-plugin-webserver/pull/3) PR is it working for you

**Comment by teobugslayer** [comment]
@DrMoriarty 
I assume the fix in the linked PR works for you. In case you face some problems, please re-open this PR.

**Pull request closed without merging**
